name: "Release Ruby Gems & NPM Packages"

on:
  workflow_call:
  workflow_dispatch:
  release:
    types:
      - created
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: "Hello!"
      run: echo "Hello!"

