name: "Release Ruby Gems & NPM Packages"

on:
  workflow_call:
    inputs:
      tag_name:
        required: true
        type: string
  workflow_dispatch:
  release:
    types:
      - created
      - published

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - name: "Hello! with $TAG_NAME"
      run: echo "Hello! $TAG_NAME"
      env:
        TAG_NAME: ${{ inputs.tag_name }}

