name: "Tag, Relase & Push"
on:
  # Should trigger only when a Pull Request is Merged
  # (the action will not create the Tag if the Pull Request is discarded - closed without merge)
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  TagOnPR:
    name: Tag on Pull Request merge
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-on-pr-merge.outputs.tag }}
    # This 'if' condition is important for ensuring the workflow only runs for merged PRs
    #  (avoid running when a PR is discarded - closed without merging)
    if: github.event.pull_request.merged == true
    steps:
      - name: Tag on PR merge
        id: tag-on-pr-merge
        uses: David-Lor/action-tag-on-pr-merge@main
        with:
          push-tag: true
      - name: Print fetched tag
        run: echo "${{ steps.tag-on-pr-merge.outputs.tag }}"
  release:
    needs: TagOnPR
    outputs:
      tag: ${{ needs.TagOnPR.outputs.tag }}
    if: ${{ startsWith(needs.TagOnPR.outputs.tag, 'v') }}
      # If we created a `v*` tag then we checkout the repo and tag a release.
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.TagOnPR.outputs.tag }}
          generate_release_notes: true
  push:
    needs: release
    if: ${{ startsWith(needs.TagOnPR.outputs.tag, 'v') }}
    uses: ./.github/workflows/release.yml
    secrets: inherit
    env:
      TAG_NAME: ${{ needs.release.outputs.tag }}
